name: Flutter CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v1
          with:
            channel: 'beta'
      - run: flutter pub get
      - run: flutter build web